import type { ProItem } from '@/types/components-utils'
export const columnList: ProItem[] = [
  {
    width: '120px',
    dataIndex: 'id',
    title: '主键',
    isSearch: false,
    isForm: false,
    noTable: true,
  },
  {
    width: '120px',
    dataIndex: 'path',
    title: '请求路径',
    valueType: 'input',
    isSearch: true,
    noTable: false,
  },
  {
    width: '120px',
    dataIndex: 'method',
    title: '请求方式',
    valueType: 'input',
    isSearch: true,
    noTable: false,
  },
  {
    width: '120px',
    dataIndex: 'ip',
    title: 'ip',
    valueType: 'input',
    isSearch: true,

    noTable: false,
  },
  {
    width: 'auto',
    dataIndex: 'query',
    title: 'query',
    isSearch: false,
    noTable: false,
  },
  {
    width: '120px',
    dataIndex: 'params',
    title: 'params',
    isSearch: false,
    noTable: false,
  },
  {
    width: 'auto',
    dataIndex: 'body',
    title: 'body',
    isSearch: false,
    noTable: false,
  },
  {
    width: '120px',
    dataIndex: 'result',
    title: '响应结果',
    isSearch: false,
    noTable: true,
  },
  {
    width: '120px',
    dataIndex: 'error',
    title: '错误信息',
    isSearch: false,
    noTable: true,
    noInfo: false,
  },
  {
    width: '120px',
    dataIndex: 'time',
    title: '响应时间',
    isSearch: false,
    noTable: false,
  },
  {
    width: '120px',
    dataIndex: 'createdBy',
    title: '操作人',
    valueType: 'input',
    isSearch: true,
    noTable: false,
  },
  {
    width: '120px',
    dataIndex: 'status',
    title: '操作状态',
    valueType: 'select',
    isSearch: true,
    noTable: false,
    renderType: 'dict',
    option: [
      {
        label: '成功',
        value: 1,
      },
      {
        label: '失败',
        value: 0,
      },
    ],
  },
  {
    width: '200px',
    dataIndex: 'createdAt',
    title: '操作时间',
    isSearch: false,
    noTable: false,
  },
  {
    width: '100px',
    dataIndex: 'action',
    fixed: 'right',
    title: '操作',
    noInfo: true,
  },
]
